apiVersion : apps/v1
kind: Deployment
metadata:
  name: shorturl-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shorturl-app
  template:
    metadata:
      labels:
        app: shorturl-app
    spec:
      containers:
        - name: shorturl-app
          image: sansaedemoacr.azurecr.io/shorturl-app
          ports:
          - containerPort: 8080