apiVersion : apps/v1
kind: Deployment
metadata:
  name: shorturl-app-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shorturl-app
  template:
    metadata:
      labels:
        app: shorturl-app
    spec:
      containers:
        - name: shorturl-app
          image: cvpdemoacr.azurecr.io/shorturl-app
          env:
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: jvm-config
                key: JAVA_OPTS_DEV
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: REDIS_PORT
          - name: REDIS_SSL_ENABLE
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: REDIS_SSL_ENABLE
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_PASSWORD
          ports:
          - containerPort: 8080