apiVersion: v1
kind: Service
metadata:
    name: shorturl-app-service
    labels:
        env: prod
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: shorturl-app